#
# Custom Cops
#

# Layout
Layout/MultilineArrayElementLayout:
  Enabled: true
Layout/MultilineHashElementLayout:
  Enabled: true
Layout/MultilineMethodCallLayout:
  Enabled: true
  IgnoredMethods:
    # Rspec
    - it
    - describe
    - context
    - to
    - not_to
    - to_not
    - be
    - be_a
    - be_an
    - be_between
    - be_falsey
    - be_kind_of
    - be_instance_of
    - be_truthy
    - be_within
    - eq
    - eql
    - end_with
    - include
    - match
    - raise_error
    - respond_to
    - start_with

Layout/MultilineMethodDefinitionLayout:
  Enabled: true

# Lint
Lint/ParametersBeforeBlock:
  Enabled: true
  IgnoredMethods:
    - it
    - describe
    - context
    - shared_examples_for
    - it_behaves_like
    - to

# Security
Security/RegexpBypass:
  Enabled: true
  Exclude:
    - spec/**/*


# Style
Style/MultilineMethodCallParentheses:
  Enabled: true
  IgnoredMethods:
    # Rspec
    - it
    - describe
    - context
    - to
    - not_to
    - to_not
    - be
    - be_a
    - be_an
    - be_between
    - be_falsey
    - be_kind_of
    - be_instance_of
    - be_truthy
    - be_within
    - eq
    - eql
    - end_with
    - include
    - match
    - raise_error
    - respond_to
    - start_with

Performance/ObjectIn:
  Enabled: true
  Include:
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
